WASdev/ci.docker.websphere-traditional

- base/Dockerfile.install
- base/Dockerfile.prereq
- developer/Dockerfile.install
- developer/Dockerfile.prereq
- network-deployment/appserver/updateHostAndFederateServer.sh
- network-deployment/custom/updateHostAndAddNode.sh
- network-deployment/dmgr/startDmgr.sh
- network-deployment/install/Dockerfile.install
- network-deployment/install/Dockerfile.prereq
Graceful stop for Network Deployment Components also added
>  Base moved to 16.04 , apt-get update added

- base/Dockerfile.install
- base/Dockerfile.prereq
- base/README.md
- base/Run-install-image.md
- base/Run-profile-image.md
- base/createProfileAndStartServer.sh
- base/start.sh
- base/updateHostName.py
- developer/Dockerfile.install
- developer/Dockerfile.prereq
- developer/README.md
- developer/Run-install-image.md
- developer/Run-profile-image.md
- developer/createProfileAndStartServer.sh
- developer/start.sh
- developer/updateHostName.py
- network-deployment/appserver/updateHostName.py
- network-deployment/custom/updateHostName.py
- network-deployment/dmgr/updateHostName.py
- network-deployment/install/Dockerfile.prereq
- network-deployment/install/README.md
An attempt to minimize the differences across the base, developer and nd directories and tidy up some of the whitespace along the way.
> Reconcile differences

- network-deployment/appserver/updateHostAndFederateServer.sh
- network-deployment/custom/updateHostAndAddNode.sh
WAIT option can be specified in docker-compose for building ND Cell Topology
>  WAIT option added

- base/Dockerfile.profile
- base/README.md
- base/Run-install-image.md
- base/Run-profile-image.md
- base/createProfileAndStartServer.sh
- base/start.sh
- base/updateHostName.py
- developer/Dockerfile.profile
- developer/Dockerfile.v9.install
- developer/Dockerfile.v9.prereq
- developer/README.md
- developer/Run-install-image.md
- developer/Run-profile-image.md
- developer/createProfileAndStartServer.sh
- developer/start.sh
- developer/updateHostName.py
Also updated the updateHostName script and port numbers in the README
>  SERVER_NAME variable added

- base/Dockerfile.prereq
- base/Dockerfile.v9.prereq
- network-deployment/install/Dockerfile.prereq
- network-deployment/install/Dockerfile.v9.prereq
> Avoid accumulating downloaded artifacts

- base/Dockerfile.v855.prereq
- base/Dockerfile.v9.prereq
- base/README.md
Add docs to cover v9. Move up to 9.0.0.1 fix pack and move 8.5.5 image to Java 8.
> Base image updates

- developer/versions.csv
> Add new tWAS fix pack version 9.0.0.6

- developer/versions.csv
Adding repositories for the latest tWAS fix packs.
> Add repositories for TWAS 9.0.0.7 and 8.5.5.13

- developer/versions.csv
Adding new 9.0.0.8 release repository to build.
> Add tWAS 9.0.0.8 repository

- developer/versions.csv
Publishing new product fix pack 8.5.5.14.
> Publish docker image for tWAS 8.5.5.14

- developer/versions.csv
Making available the new 9.0.0.9 release.
> Ship WebSphere traditional 9.0.0.9

- .gitignore
- developer/install/Dockerfile
Updating maintainer
Signed-off-by: Arthur De Magalhaes <ademagalhaes@gmail.com>
> Minor update

- developer/build_all
Adding debug to help with build error investigation.
> Add version build output to build log

- developer/README.md
- developer/build_all
- developer/push_all
Removing the -install tags for websphere-traditional, per Arthur's request.
> Remove install tags for websphere-traditional

- README.md
- docker-build/Dockerfile
Signed-off-by: Arthur De Magalhaes <ademagalhaes@gmail.com>
> Updating docs

- docker-build/build
- docker-build/build_all
Simplify build files to reflect the changes made to the tWAS Dockerfile.
> Update build files to match Dockerfile updates

- README.md
- docker-build/Dockerfile
- docker-build/scripts/applyConfig.sh
*  Update props location to `/work/config`
*  Use proper `chown` in examples
> Updating props config location

- docker-build/9.0.0.10/Dockerfile.offline
- docker-build/9.0.0.x/Dockerfile.offline
> Fix on Dockerfile.offline

- docker-build/9.0.0.10/Dockerfile
- docker-build/9.0.0.10/Dockerfile.offline
- docker-build/9.0.0.10/scripts/create_profile.sh
- docker-build/9.0.0.x/Dockerfile
- docker-build/9.0.0.x/Dockerfile.offline
- docker-build/9.0.0.x/scripts/create_profile.sh
Remove group was references 
Dot not install default and IVT apps
> Do not install default applicaiton & fix uid:gid

- docker-build/8.5.x/Dockerfile
- docker-build/9.0.0.10/Dockerfile
- docker-build/9.0.0.9/Dockerfile
- docker-build/9.0.0.x/Dockerfile
- samples/batch-compute-grid/Dockerfile
> Use proper label

- docker-build/9.0.0.10/Dockerfile
- docker-build/9.0.0.10/Dockerfile.offline
- docker-build/9.0.0.10/scripts/applyConfig.sh
- docker-build/9.0.0.10/scripts/set_password.sh
- docker-build/9.0.0.10/scripts/start_server.sh
- docker-build/9.0.0.9/Dockerfile
- docker-build/9.0.0.9/scripts/applyConfig.sh
- docker-build/9.0.0.9/scripts/create_profile.sh
- docker-build/9.0.0.9/scripts/set_password.sh
- docker-build/9.0.0.9/scripts/start_server.sh
- docker-build/9.0.0.x/Dockerfile
- docker-build/9.0.0.x/Dockerfile.offline
- docker-build/9.0.0.x/scripts/applyConfig.sh
- docker-build/9.0.0.x/scripts/set_password.sh
- docker-build/9.0.0.x/scripts/start_server.sh
Fixes applyConfig.sh showing error message when no .props files present
Fixes the new wsadmin password not being applied at runtime after configure.sh is called
Improves docker image to be able to run as random user id
> Script fixes and Dockerfile improvements

- docker-build/build_all.sh
Adding the ability to build UBI images.
> Add ubi image build support

- samples/batch-compute-grid/Dockerfile
Follow-up to #146  which broke this.
> Updated batch sample with group id change was->root

- docker-build/9.0.5.x/licenses/en.html
- docker-build/9.0.5.x/licenses/non_ibm_license.html
- docker-build/9.0.5.x/licenses/notices.html
Add the proper license files for the upcoming 9.0.5.0 release.
> Check in 9.0.5.0 licenses

- docker-build/8.5.x/scripts/configHPEL.py
- docker-build/8.5.x/scripts/configure_logging.sh
- docker-build/8.5.x/scripts/start_server.sh
Backported changes from 9.0.5.x start_server.sh file and added configure_logging.py and configHPEL.py scripts.
> Adding JSON capability for TWAS 8.5.x docker start in start_server.sh

- docker-build/9.0.5.2/Dockerfile.ubi8
- docker-build/9.0.5.x/Dockerfile.ubi8
> Initial drop of ubi8 Dockerfiles

- samples/hello-world/Dockerfile.ubi
- samples/hello-world/openshift/README.md
- samples/hello-world/openshift/buildah.yaml
- samples/hello-world/openshift/k8s/deployment.yaml
- samples/hello-world/openshift/k8s/route.yaml
- samples/hello-world/openshift/k8s/service.yaml
- samples/hello-world/openshift/pipeline/apply_manifest_task.yaml
- samples/hello-world/openshift/pipeline/pipeline.yaml
- samples/hello-world/openshift/pipeline/resources.yaml
- samples/hello-world/openshift/pipeline/update_deployment_task.yaml
- samples/hello-world/openshift/subscription.yaml
Add artifacts and simple recipe for installing the twas hello-world sample app using openshift pipelines.
> Openshift pipelines

- docker-build/build_all.sh
Add ability for build_all.sh script to build ubi8 images.
> Update build script to build ubi8 images

- docker-build/8.5.5.18/Dockerfile
- docker-build/8.5.5.18/Dockerfile-ubi8-amd64
- docker-build/8.5.5.18/Dockerfile-ubi8-ppc64le-notyet
- docker-build/8.5.5.19/Dockerfile
- docker-build/8.5.5.19/Dockerfile-ubi8-amd64
- docker-build/8.5.5.19/Dockerfile-ubi8-ppc64le-notyet
- docker-build/8.5.5.20/Dockerfile
- docker-build/8.5.5.20/Dockerfile-ubi8-amd64
- docker-build/8.5.5.20/Dockerfile-ubi8-ppc64le
- docker-build/9.0.5.10/Dockerfile
- docker-build/9.0.5.10/Dockerfile-ubi8
- docker-build/9.0.5.8/Dockerfile
- docker-build/9.0.5.8/Dockerfile-ubi8
- docker-build/9.0.5.9/Dockerfile
- docker-build/9.0.5.9/Dockerfile-ubi8
Removed old iFix install as it is now superseded.
Added new iFix to address log4j vulnerability.
Removed backup of fix as it is unnecessary to do a fix rollback in a docker environment and it prevents the backup from showing up in scans.
> Ph42762 install

- docker-build/8.5.5.22/Dockerfile-ubi8
- docker-build/9.0.5.12/Dockerfile-ubi8
Reverts WASdev/ci.docker.websphere-traditional#272
> Revert "Test cert generation on first container start"

- docker-build/8.5.5.21/scripts/updateKeyStorePassword.py
- docker-build/8.5.5.22/scripts/updateKeyStorePassword.py
- docker-build/8.5.5.23/scripts/updateKeyStorePassword.py
- docker-build/8.5.5.x/scripts/updateKeyStorePassword.py
- docker-build/9.0.5.12/scripts/updateKeyStorePassword.py
- docker-build/9.0.5.13/scripts/updateKeyStorePassword.py
- docker-build/9.0.5.14/scripts/updateKeyStorePassword.py
- docker-build/9.0.5.x/scripts/updateKeyStorePassword.py
Add correct number of arguments and switch to a different function format
> Update AdminTask to function properly

- .pre-commit-config.yaml
- .secrets.baseline
Also see https://github.ibm.com/WAS-CD-Area/WAS-CD-Area/issues/1485
> #1485 - Adding detect-secrets configuration files.

- README.md
Link contributing doc from the readme
> Link contributing doc from the readme
